
export const rolemenu=[

                       {
                path: '/homepage',
                name: 'homepage',
                component: 'home/homepage',
                meta: {
                    title: 'message.router.homepage',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: true,
                    isIframe: false,
                    roles: ['admin','common'],
                    icon: 'iconfont icon-shouye',
                },
            },
            {

                path: '/sysmanage',
                name: 'sysmanage',
                component:'layout/routerView/parent',
                redirect: '/homepage',
                meta: {
                    title: 'message.router.sysmanage',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'iconfont icon-xitongshezhi',
                },
                children: [


                    {
                        path: '/sysmanage/address',
                        name: 'address',
                        component: 'sysmanage/address/index',
                        meta: {
                            title: 'message.router.address',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-diqiu',
                        },

                        children: [
                            {
                                path: '/sysmanage/address/networkinterface',
                                name: 'networkinterface',
                                component: 'sysmanage/address/networkinterface/index',
                                meta: {
                                    title: 'message.router.networkinterface',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'iconfont icon-caidan',
                                },
                            },
                            {
                                path: '/sysmanage/address/serial',
                                name: 'serial',
                                component: 'sysmanage/address/serial/index',
                                meta: {
                                    title: 'message.router.serial',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'iconfont icon-zhongyingwenqiehuan',
                                },
                            },
                        ],
                    },
                    {
                        path: '/sysmanage/package',
                        name: 'package',
                        component: 'sysmanage/package/index',
                        meta: {
                            title: 'message.router.package',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon--chaifenhang',
                        },
                        children: [
                            {
                                path: '/sysmanage/package/packagedetail',
                                name: 'packagedetail',
                                component: 'sysmanage/package/packagedetail',
                                meta: {
                                    title: 'message.router.packagedetail',
                                    isLink: '',
                                    isHide: true,
                                    isKeepAlive: false,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'ele-Sunny',
                                },
                            },
                        ],

                    },
                    /*{
                        path: '/system/app',
                        name: 'app',
                        component: 'system/user/index',
                        meta: {
                            title: 'message.router.app',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-bolangnengshiyanchang',
                        },
                    },*/
                    {

                        path: '/sysmanage/messheader',
                        name: 'messheader',
                        component: 'sysmanage/messheader/index',
                        meta: {
                            title: 'message.router.messheader',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-shuxingtu',
                        },
                        children: [
                            {
                                path: '/sysmanage/messheader/messheaderdetail',
                                name: 'messheaderdetail',
                                component: 'sysmanage/messheader/messheaderdetail',
                                meta: {
                                    title: 'message.router.messheaderdetail',
                                    isLink: '',
                                    isHide: true,
                                    isKeepAlive: false,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'ele-Sunny',
                                },
                            },
                        ],
                    }, {
                        path: '/sysmanage/messbody',
                        name: 'messbody',
                        component: 'sysmanage/messbody/index',
                        meta: {
                            title: 'message.router.messbody',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-ziti',
                        },
                        children: [
                            {
                                path: '/sysmanage/messbody/messbodydetail',
                                name: 'messbodydetail',
                                component: 'sysmanage/messbody/messbodydetail',
                                meta: {
                                    title: 'message.router.messbodydetail',
                                    isLink: '',
                                    isHide: true,
                                    isKeepAlive: false,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'ele-Sunny',
                                },
                            },
                        ],
                    }, {
                        path: '/sysmanage/messtraslate',
                        name: 'messtraslate',
                        component: 'sysmanage/messtraslate/index',
                        meta: {
                            title: 'message.router.messtraslate',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-neiqianshujuchucun',
                        },
                        children: [
                            {
                                path: '/sysmanage/messtraslate/messtraslatedetail',
                                name: 'messtraslatedetail',
                                component: 'sysmanage/messtraslate/messtraslatedetail',
                                meta: {
                                    title: 'message.router.messtraslatedetail',
                                    isLink: '',
                                    isHide: true,
                                    isKeepAlive: false,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'iconfont icon-zujian',
                                },
                            },
                        ],
                    }
                    , {
                        path: '/sysmanage/fieldcollection',
                        name: 'fieldcollection',
                        component: 'sysmanage/fieldcollection/index',
                        meta: {
                            title: 'message.router.fieldcollection',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon--chaifenhang',
                        },
                        children: [{
                            path: '/sysmanage/fieldcollection/fieldsdetail',
                            name: 'fieldsdetail',
                             component: 'sysmanage/fieldcollection/detail',
                            meta: {
                                title: 'message.router.fieldsdetail',
                                isLink: '',
                                isHide: true,
                                isKeepAlive: false,
                                isAffix: false,
                                isIframe: false,
                                roles: ['admin', 'common'],
                                icon: 'iconfont icon-ico_shuju',
                            },

                        }],
                    }
                ]

            },
            {

                path: '/flowmanage',
                name: 'flowmanage',
                component:'layout/routerView/parent',
                redirect: '/homepage',
                meta: {
                    title: 'message.router.flowmanage',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'iconfont icon-tupianyulan',
                },
                children: [


                    {
                        path: '/flowmanage/flowdesign',
                        name: 'flowdesign',
                        component: 'flowmanage/flowdesign/index',
                        meta: {
                            title: 'message.router.flowdesign',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-putong',
                        },
                        children: [

                            {
                                path: '/flowmanage/flowdesign/flowdesigndetail2',
                                name: 'flowdesigndetail2',
                                component: 'flowmanage/flowdesign/flowdesigndetail2/index',
                                meta: {
                                    title: 'message.router.flowdesigndetail2',
                                    isLink: '',
                                    isHide: true,
                                    isKeepAlive: false,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'ele-Sunny',
                                },
                            },
                        ],
                    },
                    {
                        path: '/flowmanage/globalvar',
                        name: 'globalvar',
                        component: 'flowmanage/globalvar/index',
                        meta: {
                            title: 'message.router.globalvar',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-diqiu1',
                        },
                    }, {
                        path: '/flowmanage/specialnode',
                        name: 'specialnode',
                        component: 'flowmanage/specialnode/index',
                        meta: {
                            title: 'message.router.specialnode',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-zujian',
                        },
                    }
                ]

            },
              {

                path: '/distribution',
                name: 'distribution',
                component:'layout/routerView/parent',
                redirect: '/homepage',
                meta: {
                    title: 'message.router.distribution',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'ele-Guide',
                },
                children: [


                    {
                        path: '/distribution/gateway',
                        name: 'gateway',
                        component: 'distribution/gateway/index',
                        meta: {
                            title: 'message.router.gateway',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Cpu',
                        },
                    },
                    {
                        path: '/distribution/flowdistribution',
                        name: 'flowdistribution',
                        component: 'distribution/flowdistribution/index',
                        meta: {
                            title: 'message.router.flowdistribution',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Connection',
                        },
                    }
                ]

            },
            {

                path: '/pluginmanage',
                name: 'pluginmanage',
                component:'layout/routerView/parent',
                redirect: '/system/menu',
                meta: {
                    title: 'message.router.pluginmanage',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'iconfont icon-zidingyibuju',
                },
                children: [


                    {
                        path: '/pluginmanage/sysplug',
                        name: 'sysplug',
                        component: 'pluginmanage/sysplug/index',
                        meta: {
                            title: 'message.router.sysplug',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-fuwenbenkuang',
                        },
                    },
                    {
                        path: '/pluginmanage/funcplug',
                        name: 'funcplug',
                        component: 'pluginmanage/funcplug/index',
                        meta: {
                            title: 'message.router.funcplug',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-siweidaotu',
                        },
                    }
                ]

            },

            {

                path: '/systemadmin',
                name: 'systemadmin',
                component:'layout/routerView/parent',
                redirect: '/system/menu',
                meta: {
                    title: 'message.router.systemadmin',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'iconfont icon-gongju',
                },
                children: [


                    {
                        path: '/systemadmin/usermanage',
                        name: 'usermanage',
                        component: 'systemadmin/usermanage/index',
                        meta: {
                            title: 'message.router.usermanage',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-icon-',
                        },
                    },
                    {
                        path: '/systemadmin/rolemanage',
                        name: 'rolemanage',
                        component: 'systemadmin/rolemanage/index',
                        meta: {
                            title: 'message.router.rolemanage',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-shouye',
                        },
                    },
                    {
                        path: '/systemadmin/logmanage',
                        name: 'logmanage',
                        component: 'systemadmin/logmanage/index',
                        meta: {
                            title: 'message.router.logmanage',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-xuanzeqi',
                        },
                    }
                ]

            },
            {
                path: '/home',
                name: 'home',
                component: 'home/index',
                meta: {
                    title: 'message.router.home',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: true,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-shouye',
                },
            },
            {
                path: '/system',
                name: 'system',
                component:'layout/routerView/parent',
                redirect: '/system/menu',
                meta: {
                    title: 'message.router.system',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-xitongshezhi',
                },
                children: [
                    {
                        path: '/system/menu',
                        name: 'systemMenu',
                        component: 'system/menu/index',
                        meta: {
                            title: 'message.router.systemMenu',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                    {
                        path: '/system/role',
                        name: 'systemRole',
                        component: 'system/role/index',
                        meta: {
                            title: 'message.router.systemRole',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-ColdDrink',
                        },
                    },
                    {
                        path: '/system/user',
                        name: 'systemUser',
                        component: 'system/user/index',
                        meta: {
                            title: 'message.router.systemUser',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-icon-',
                        },
                    },
                    {
                        path: '/system/dept',
                        name: 'systemDept',
                        component: 'system/dept/index',
                        meta: {
                            title: 'message.router.systemDept',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-OfficeBuilding',
                        },
                    },
                    {
                        path: '/system/dic',
                        name: 'systemDic',
                        component: 'system/dic/index',
                        meta: {
                            title: 'message.router.systemDic',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-SetUp',
                        },
                    },
                ],
            },
            {
                path: '/limits',
                name: 'limits',
                component:'layout/routerView/parent',
                redirect: '/limits/frontEnd',
                meta: {
                    title: 'message.router.limits',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-quanxian',
                },
                children: [
                    {
                        path: '/limits/frontEnd',
                        name: 'limitsFrontEnd',
                        component:'layout/routerView/parent',
                        redirect: '/limits/frontEnd/page',
                        meta: {
                            title: 'message.router.limitsFrontEnd',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: '',
                        },
                        children: [
                            {
                                path: '/limits/frontEnd/page',
                                name: 'limitsFrontEndPage',
                                component: 'limits/frontEnd/page/index',
                                meta: {
                                    title: 'message.router.limitsFrontEndPage',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin'],
                                    icon: '',
                                },
                            },
                            {
                                path: '/limits/frontEnd/btn',
                                name: 'limitsFrontEndBtn',
                                component: 'limits/frontEnd/btn/index',
                                meta: {
                                    title: 'message.router.limitsFrontEndBtn',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin'],
                                    icon: '',
                                },
                            },
                        ],
                    },
                    {
                        path: '/limits/backEnd',
                        name: 'limitsBackEnd',
                        component:'layout/routerView/parent',
                        meta: {
                            title: 'message.router.limitsBackEnd',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: '',
                        },
                        children: [
                            {
                                path: '/limits/backEnd/page',
                                name: 'limitsBackEndEndPage',
                                component: 'limits/backEnd/page/index',
                                meta: {
                                    title: 'message.router.limitsBackEndEndPage',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin'],
                                    icon: '',
                                },
                            },
                        ],
                    },
                ],
            },
            {
                path: '/menu',
                name: 'menu',
                component:'layout/routerView/parent',
                redirect: '/menu/menu1',
                meta: {
                    title: 'message.router.menu',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-caidan',
                },
                children: [
                    {
                        path: '/menu/menu1',
                        name: 'menu1',
                        component:'layout/routerView/parent',
                        redirect: '/menu/menu1/menu11',
                        meta: {
                            title: 'message.router.menu1',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                        children: [
                            {
                                path: '/menu/menu1/menu11',
                                name: 'menu11',
                                component: 'menu/menu1/menu11/index',
                                meta: {
                                    title: 'message.router.menu11',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin'],
                                    icon: 'iconfont icon-caidan',
                                },
                            },
                            {
                                path: '/menu/menu1/menu12',
                                name: 'menu12',
                                component:'layout/routerView/parent',
                                redirect: '/menu/menu1/menu12/menu121',
                                meta: {
                                    title: 'message.router.menu12',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin'],
                                    icon: 'iconfont icon-caidan',
                                },
                                children: [
                                    {
                                        path: '/menu/menu1/menu12/menu121',
                                        name: 'menu121',
                                        component: 'menu/menu1/menu12/menu121/index',
                                        meta: {
                                            title: 'message.router.menu121',
                                            isLink: '',
                                            isHide: false,
                                            isKeepAlive: true,
                                            isAffix: false,
                                            isIframe: false,
                                            roles: ['admin', 'common'],
                                            icon: 'iconfont icon-caidan',
                                        },
                                    },
                                    {
                                        path: '/menu/menu1/menu12/menu122',
                                        name: 'menu122',
                                        component: 'menu/menu1/menu12/menu122/index',
                                        meta: {
                                            title: 'message.router.menu122',
                                            isLink: '',
                                            isHide: false,
                                            isKeepAlive: true,
                                            isAffix: false,
                                            isIframe: false,
                                            roles: ['admin', 'common'],
                                            icon: 'iconfont icon-caidan',
                                        },
                                    },
                                ],
                            },
                            {
                                path: '/menu/menu1/menu13',
                                name: 'menu13',
                                component: 'menu/menu1/menu13/index',
                                meta: {
                                    title: 'message.router.menu13',
                                    isLink: '',
                                    isHide: false,
                                    isKeepAlive: true,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'iconfont icon-caidan',
                                },
                            },
                        ],
                    },
                    {
                        path: '/menu/menu2',
                        name: 'menu2',
                        component: 'menu/menu2/index',
                        meta: {
                            title: 'message.router.menu2',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                ],
            },
            {
                path: '/fun',
                name: 'funIndex',
                component:'layout/routerView/parent',
                redirect: '/fun/tagsView',
                meta: {
                    title: 'message.router.funIndex',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-crew_feature',
                },
                children: [
                    {
                        path: '/fun/tagsView',
                        name: 'funTagsView',
                        component: 'fun/tagsView/index',
                        meta: {
                            title: 'message.router.funTagsView',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Pointer',
                        },
                    },
                    {
                        path: '/fun/countup',
                        name: 'funCountup',
                        component: 'fun/countup/index',
                        meta: {
                            title: 'message.router.funCountup',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Odometer',
                        },
                    },
                    {
                        path: '/fun/wangEditor',
                        name: 'funWangEditor',
                        component: 'fun/wangEditor/index',
                        meta: {
                            title: 'message.router.funWangEditor',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-fuwenbenkuang',
                        },
                    },
                    {
                        path: '/fun/cropper',
                        name: 'funCropper',
                        component: 'fun/cropper/index',
                        meta: {
                            title: 'message.router.funCropper',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-caijian',
                        },
                    },
                    {
                        path: '/fun/qrcode',
                        name: 'funQrcode',
                        component: 'fun/qrcode/index',
                        meta: {
                            title: 'message.router.funQrcode',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-ico',
                        },
                    },
                    {
                        path: '/fun/echartsMap',
                        name: 'funEchartsMap',
                        component: 'fun/echartsMap/index',
                        meta: {
                            title: 'message.router.funEchartsMap',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-ditu',
                        },
                    },
                    {
                        path: '/fun/printJs',
                        name: 'funPrintJs',
                        component: 'fun/printJs/index',
                        meta: {
                            title: 'message.router.funPrintJs',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Printer',
                        },
                    },
                    {
                        path: '/fun/clipboard',
                        name: 'funClipboard',
                        component: 'fun/clipboard/index',
                        meta: {
                            title: 'message.router.funClipboard',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-DocumentCopy',
                        },
                    },
                    {
                        path: '/fun/gridLayout',
                        name: 'funGridLayout',
                        component: 'fun/gridLayout/index',
                        meta: {
                            title: 'message.router.funGridLayout',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-tuodong',
                        },
                    },
                    {
                        path: '/fun/splitpanes',
                        name: 'funSplitpanes',
                        component: 'fun/splitpanes/index',
                        meta: {
                            title: 'message.router.funSplitpanes',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon--chaifenlie',
                        },
                    },
                ],
            },
            {
                path: '/pages',
                name: 'pagesIndex',
                component:'layout/routerView/parent',
                redirect: '/pages/filtering',
                meta: {
                    title: 'message.router.pagesIndex',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-fuzhiyemian',
                },
                children: [
                    {
                        path: '/pages/filtering',
                        name: 'pagesFiltering',
                        component: 'pages/filtering/index',
                        meta: {
                            title: 'message.router.pagesFiltering',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Sell',
                        },
                        /**
                         * 注意此处详情写法：
                         * 1、嵌套进父级里时，面包屑显示为：首页/页面/过滤筛选组件/过滤筛选组件详情
                         * 2、不嵌套进父级时，面包屑显示为：首页/页面/过滤筛选组件/过滤筛选组件详情
                         * 3、想要父级不高亮，面包屑显示为：首页/页面/过滤筛选组件详情，设置路径为：/pages/filteringDetails
                         */
                        children: [
                            {
                                path: '/pages/filtering/details',
                                name: 'pagesFilteringDetails',
                                component: 'pages/filtering/details',
                                meta: {
                                    title: 'message.router.pagesFilteringDetails',
                                    isLink: '',
                                    isHide: true,
                                    isKeepAlive: false,
                                    isAffix: false,
                                    isIframe: false,
                                    roles: ['admin', 'common'],
                                    icon: 'ele-Sunny',
                                },
                            },
                        ],
                    },
                    {
                        path: '/pages/filtering/details1',
                        name: 'pagesFilteringDetails1',
                        component: 'pages/filtering/details1',
                        meta: {
                            title: 'message.router.pagesFilteringDetails1',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: false,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Sunny',
                        },
                    },
                    {
                        path: '/pages/iocnfont',
                        name: 'pagesIocnfont',
                        component: 'pages/iocnfont/index',
                        meta: {
                            title: 'message.router.pagesIocnfont',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Present',
                        },
                    },
                    {
                        path: '/pages/element',
                        name: 'pagesElement',
                        component: 'pages/element/index',
                        meta: {
                            title: 'message.router.pagesElement',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Eleme',
                        },
                    },
                    {
                        path: '/pages/awesome',
                        name: 'pagesAwesome',
                        component: 'pages/awesome/index',
                        meta: {
                            title: 'message.router.pagesAwesome',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-SetUp',
                        },
                    },
                    {
                        path: '/pages/formAdapt',
                        name: 'pagesFormAdapt',
                        component: 'pages/formAdapt/index',
                        meta: {
                            title: 'message.router.pagesFormAdapt',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-biaodan',
                        },
                    },
                    {
                        path: '/pages/tableRules',
                        name: 'pagesTableRules',
                        component: 'pages/tableRules/index',
                        meta: {
                            title: 'message.router.pagesTableRules',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-jiliandongxuanzeqi',
                        },
                    },
                    {
                        path: '/pages/formI18n',
                        name: 'pagesFormI18n',
                        component: 'pages/formI18n/index',
                        meta: {
                            title: 'message.router.pagesFormI18n',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-diqiu',
                        },
                    },
                    {
                        path: '/pages/formRules',
                        name: 'pagesFormRules',
                        component: 'pages/formRules/index',
                        meta: {
                            title: 'message.router.pagesFormRules',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-shuxing',
                        },
                    },
                    {
                        path: '/pages/listAdapt',
                        name: 'pagesListAdapt',
                        component: 'pages/listAdapt/index',
                        meta: {
                            title: 'message.router.pagesListAdapt',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-chazhaobiaodanliebiao',
                        },
                    },
                    {
                        path: '/pages/waterfall',
                        name: 'pagesWaterfall',
                        component: 'pages/waterfall/index',
                        meta: {
                            title: 'message.router.pagesWaterfall',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-zidingyibuju',
                        },
                    },
                    {
                        path: '/pages/steps',
                        name: 'pagesSteps',
                        component: 'pages/steps/index',
                        meta: {
                            title: 'message.router.pagesSteps',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-step',
                        },
                    },
                    {
                        path: '/pages/preview',
                        name: 'pagesPreview',
                        component: 'pages/preview/index',
                        meta: {
                            title: 'message.router.pagesPreview',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-15tupianyulan',
                        },
                    },
                    {
                        path: '/pages/waves',
                        name: 'pagesWaves',
                        component: 'pages/waves/index',
                        meta: {
                            title: 'message.router.pagesWaves',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-bolangneng',
                        },
                    },
                    {
                        path: '/pages/tree',
                        name: 'pagesTree',
                        component: 'pages/tree/index',
                        meta: {
                            title: 'message.router.pagesTree',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-shuxingtu',
                        },
                    },
                    {
                        path: '/pages/drag',
                        name: 'pagesDrag',
                        component: 'pages/drag/index',
                        meta: {
                            title: 'message.router.pagesDrag',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Pointer',
                        },
                    },
                    {
                        path: '/pages/lazyImg',
                        name: 'pagesLazyImg',
                        component: 'pages/lazyImg/index',
                        meta: {
                            title: 'message.router.pagesLazyImg',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-PictureFilled',
                        },
                    },
                    {
                        path: '/pages/dynamicForm',
                        name: 'pagesDynamicForm',
                        component: 'pages/dynamicForm/index',
                        meta: {
                            title: 'message.router.pagesDynamicForm',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-wenducanshu-05',
                        },
                    },
                    {
                        path: '/pages/workflow',
                        name: 'pagesWorkflow',
                        component: 'pages/workflow/index',
                        meta: {
                            title: 'message.router.pagesWorkflow',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Connection',
                        },
                    },
                ],
            },
            {
                path: '/make',
                name: 'makeIndex',
                component:'layout/routerView/parent',
                redirect: '/make/selector',
                meta: {
                    title: 'message.router.makeIndex',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-siweidaotu',
                },
                children: [
                    {
                        path: '/make/selector',
                        name: 'makeSelector',
                        component: 'make/selector/index',
                        meta: {
                            title: 'message.router.makeSelector',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-xuanzeqi',
                        },
                    },
                    {
                        path: '/make/noticeBar',
                        name: 'makeNoticeBar',
                        component: 'make/noticeBar/index',
                        meta: {
                            title: 'message.router.makeNoticeBar',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-Bell',
                        },
                    },
                    {
                        path: '/make/svgDemo',
                        name: 'makeSvgDemo',
                        component: 'make/svgDemo/index',
                        meta: {
                            title: 'message.router.makeSvgDemo',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'fa fa-thumbs-o-up',
                        },
                    },
                    {
                        path: '/make/tableDemo',
                        name: 'makeTableDemo',
                        component: 'make/tableDemo/index',
                        meta: {
                            title: 'message.router.makeTableDemo',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'iconfont icon-shuju',
                        },
                    },
                ],
            },
            {
                path: '/params',
                name: 'paramsIndex',
                component:'layout/routerView/parent',
                redirect: '/params/common',
                meta: {
                    title: 'message.router.paramsIndex',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-zhongduancanshu',
                },
                children: [
                    {
                        path: '/params/common',
                        name: 'paramsCommon',
                        component: 'params/common/index',
                        meta: {
                            title: 'message.router.paramsCommon',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-putong',
                        },
                    },
                    {
                        path: '/params/common/details',
                        name: 'paramsCommonDetails',
                        component: 'params/common/details',
                        meta: {
                            title: 'message.router.paramsCommonDetails',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Comment',
                        },
                    },
                    {
                        path: '/params/dynamic',
                        name: 'paramsDynamic',
                        component: 'params/dynamic/index',
                        meta: {
                            title: 'message.router.paramsDynamic',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-dongtai',
                        },
                    },
                    /**
                     * tagsViewName 为要设置不同的 "tagsView 名称" 字段
                     * 如若需设置不同 "tagsView 名称"，tagsViewName 字段必须要有
                     */
                    {
                        path: '/params/dynamic/details/:t/:id/:tagsViewName',
                        name: 'paramsDynamicDetails',
                        component: 'params/dynamic/details',
                        meta: {
                            title: 'message.router.paramsDynamicDetails',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Lightning',
                        },
                    },
                ],
            },
            {
                path: '/visualizing',
                name: 'visualizingIndex',
                component:'layout/routerView/parent',
                redirect: '/visualizing/visualizingLinkDemo1',
                meta: {
                    title: 'message.router.visualizingIndex',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-ChatLineRound',
                },
                /**
                 * 打开内置全屏
                 * component 都为 `() => import('/@/layout/routerView/link')`
                 * isLink 链接为内置的路由地址，地址为 staticRoutes 中定义
                 */
                children: [
                    {
                        path: '/visualizing/visualizingLinkDemo1',
                        name: 'visualizingLinkDemo1',
                        component:'layout/routerView/link',
                        meta: {
                            title: 'message.router.visualizingLinkDemo1',
                            isLink: '/visualizingDemo1',
                            isHide: false,
                            isKeepAlive: false,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caozuo-wailian',
                        },
                    },
                    {
                        path: '/visualizing/visualizingLinkDemo2',
                        name: 'visualizingLinkDemo2',
                        component:'layout/routerView/link',
                        meta: {
                            title: 'message.router.visualizingLinkDemo2',
                            isLink: '/visualizingDemo2',
                            isHide: false,
                            isKeepAlive: false,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caozuo-wailian',
                        },
                    },
                ],
            },
            {
                path: '/chart',
                name: 'chartIndex',
                component: 'chart/index',
                meta: {
                    title: 'message.router.chartIndex',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-ico_shuju',
                },
            },
            {
                path: '/personal',
                name: 'personal',
                component: 'personal/index',
                meta: {
                    title: 'message.router.personal',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'iconfont icon-gerenzhongxin',
                },
            },
            {
                path: '/tools',
                name: 'tools',
                component: 'tools/index',
                meta: {
                    title: 'message.router.tools',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-gongju',
                },
            },
            {
                path: '/link',
                name: 'layoutLinkView',
                component:'layout/routerView/link',
                meta: {
                    title: 'message.router.layoutLinkView',
                    isLink: 'https://element-plus.gitee.io/#/zh-CN/component/installation',
                    isHide: false,
                    isKeepAlive: false,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'iconfont icon-caozuo-wailian',
                },
            },
            {
                path: '/iframesOne',
                name: 'layoutIframeViewOne',
                component:'layout/routerView/iframes',
                meta: {
                    title: 'message.router.layoutIframeViewOne',
                    isLink: 'https://nodejs.org/zh-cn/',
                    isHide: false,
                    isKeepAlive: false,
                    isAffix: false,
                    isIframe: true,
                    roles: ['admin'],
                    icon: 'iconfont icon-neiqianshujuchucun',
                },
            },
            {
                path: '/iframesTwo',
                name: 'layoutIframeViewTwo',
                component:'layout/routerView/iframes',
                meta: {
                    title: 'message.router.layoutIframeViewTwo',
                    isLink: 'https://undraw.co/illustrations',
                    isHide: false,
                    isKeepAlive: false,
                    isAffix: false,
                    isIframe: true,
                    roles: ['admin'],
                    icon: 'iconfont icon-neiqianshujuchucun',
                },
            },
        ]

